### ISSUE TITLE
[Bug] As GM target indicator is avatar instead of selected token

### ISSUE THREAD

**Issue by lozalojo** [theripper93/Smart-Target#13]
Using:
Core v0.8.8 (lastest)
HavlockV's Call of Cthulhu 7th v0.6.0 (lastest)
Smart Target v0.5.2 (lastest)

As GM, I select a NPC and target a PC to attack:

Seems that it is ok:

![](https://i.ibb.co/bJcKFKQ/68747470733a2f2f692e6962622e636f2f6d7170524b64762f73637265656e73686f742d3233322e6a7067.jpg)

But what the players see is this:

![](https://i.ibb.co/jyp32F8/68747470733a2f2f692e6962622e636f2f33344c313542342f73637265656e73686f742d3233332e6a7067.jpg)

Players see the avatar (a Lovecraft photo) instead of the token targetting them.

Also, another thing I've noticed is that as GM I cannot select one NPC, target a PC and then select another NPC and target a second PC, the first selection is removed, and only shows the last target of the last selected token. Not sure if it is intentional.

**Comment by lozalojo** [comment]
I add my Smart Target configuration:

![](https://i.ibb.co/VNvNjsw/screenshot-91.jpg)
![](https://i.ibb.co/W0zCxMd/screenshot-92.jpg)
![](https://i.ibb.co/MczNCvP/screenshot-93.jpg)

**Comment by Razeick** [comment]
Also getting the same issue. Below are my settings
![image](https://user-images.githubusercontent.com/56274169/125098104-bde39880-e0a4-11eb-8996-8cf7cca0d763.png)
![image](https://user-images.githubusercontent.com/56274169/125098190-d0f66880-e0a4-11eb-9893-63afecb84dfb.png)

**Comment by theripper93** [comment]
This option will be removed and will not be worked on

**Comment by theripper93** [comment]
i lied i added the feature
