### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Fyorl** [theripper93/Smart-Target#15]
Hi,

I noticed that this project lifts a large portion of code from the `easy-target` module. In general this is permitted by the GPL3 license that it is licensed under, however, your project appears to be licensed under an Apache 2.0 license. This is a violation of the terms of the GPL3 which require any modifications of the software to also be distributed under the terms of the GPL3.

Here is the relevant part of the license, §5b-c:
```
5. Conveying Modified Source Versions.

  You may convey a work based on the Program, or the modifications to
produce it from the Program, in the form of source code under the
terms of section 4, provided that you also meet all of these conditions:

    [ ... ]

    b) The work must carry prominent notices stating that it is
    released under this License and any conditions added under section
    7.  This requirement modifies the requirement in section 4 to
    "keep intact all notices".

    c) You must license the entire work, as a whole, under this
    License to anyone who comes into possession of a copy.  This
    License will therefore apply, along with any applicable section 7
    additional terms, to the whole of the work, and all its parts,
    regardless of how they are packaged.  This License gives no
    permission to license the work in any other way, but it does not
    invalidate such permission if you have separately received it.
```

Please could you let me know how you plan to address this. Re-licensing the project under the GPL3 would be ideal, I think, if possible. Otherwise I believe the GPL3-licensed code would have to be either removed or rewritten.

**Comment by theripper93** [comment]
Terribly sorry it was originally original code but contributors added code without informing me of it having a licence, licence changed to gpl3
