### ISSUE TITLE
Change "Click to Target" to be a "world" setting

### ISSUE THREAD

**Issue by Puddinglord** [theripper93/Smart-Target#20]
Currently, this setting only applies to the current user that selected the setting. I know you can push the setting to users using a module but changing the type of setting to `world` would do this and make sure I don't forget to change it.

I play in PFS (Pathfinder Society) and have a new group every week so new people are always logging in and I direct them to just click to target and sometimes it doesn't work because I didn't push the setting.

**Comment by theripper93** [comment]
for every person that asks for it to be global there is one that asks for it to be local, if you really need it you can change 1 word in the code and cusomize it to your needs

**Comment by Puddinglord** [comment]
I'm using a hosting service that doesn't provide command-line access. So people in my position can't do what you're suggesting. 

May we compromise with a dropdown selection of local and global?

**Comment by theripper93** [comment]
that's not something you can do, i would have to double the setting, then if someone asks for it to be like that on onther settings as well should i then double every setting? unfortunatelly modules can't be custom tailored to evey user in existance, so you will have to make do with socket settings

**Comment by dmrickey** [comment]
@Puddinglord 
You want a mod called [Socket Settings](https://foundryvtt.com/packages/SocketSettings). It adds a sync button to push settings from the GM to any logged in players
![image](https://user-images.githubusercontent.com/3664822/138194101-44c03aa4-3183-4863-ad03-5a7c24669aaf.png)
