### ISSUE TITLE
Feature Request: Release targets on alt left-click

### ISSUE THREAD

**Issue by jalensailin** [theripper93/Smart-Target#26]
I think that alt left-clicking an empty space on the canvas should release all targeted objects. I did notice a button to 'Clear all Targets' but I think it is a more natural behavior to alt-click into an empty space. Thank you for the great module and your consideration of this feature :)

**Comment by theripper93** [comment]
i'm afraid that will not work as it will conflict with the alt clicking on canvas to target within a template, if i figure out a way i'll give it some thought, for now tho no new features are planned. I might reconsider after v9 hits

**Comment by jalensailin** [comment]
Thanks for the quick response, understood
