### ISSUE TITLE
Can't see portraits on targeted ennemies

### ISSUE THREAD

**Issue by remiverdel** [theripper93/Smart-Target#27]
Hi,

I've managed to install smart target and make the new crosshair work (awesome btw). But I can't see any player portrait on selected targets. As a GM I can't know who is targeting who which is strange because I check the correct option in the module settings.

Cheers

**Comment by theripper93** [comment]
make sure your players have assigned characters, make sure the images are not getting blocked by cors, make sure you have the option enabled, check with other mods disabled, if you still can't figure it out bring it to the discord, as the git is reserved to bugs
