### ISSUE TITLE
Weird targeting behavior when switching token selection

### ISSUE THREAD

**Issue by dmrickey** [theripper93/Smart-Target#28]
As the GM, if I have a Token1 selected and target Token5, then change my selection to Token2, and then hover my cursor back over Token5, then the target token indicator on the player screen changes to the newly selected token. 

1. if I select Token1, and target Token5, then on the player screen it shows the Token1 indicator
2. a. If I then select Token2, and hover the cursor over the already targeted Token5, the player screen token indicator changes to Token5
2. b. If I instead select Token2, then unselect Token2, and hover the cursor over the target, the player screen token indicator still changes to the last selected token

There doesn't seem to be any way to show targeting indicators for multiple tokens simultaneously.

Bonus question - is there any way to show the token indicator on the GM screen? I only see the targeting reticle and I'd like to see the token indicator as well to indicate which token I had selected when I targeted a token.

**Comment by theripper93** [comment]
fixed
bonus question - no plans to add that sorry
