### ISSUE TITLE
Target image X offset doesn't move the icon, just the image inside the icon

### ISSUE THREAD

**Issue by susscribe** [theripper93/Smart-Target#31]
as stated, 1 example, on the left side a player account logged client while on the right there's the GM account logged client:
![image](https://user-images.githubusercontent.com/87147923/139597783-8787ea12-0b11-42f8-9938-8e3245a32a16.png)

when a change is made:
![image](https://user-images.githubusercontent.com/87147923/139597795-5a068b6f-081c-469e-9666-40281f45a2f8.png)

it may be my wild imagination but i seem to remember when the module moved the targeting icon altogether instead of the image inside the icon. moving the image without the icon is pointless as it will still overlap with other icons displayed on the token. moving the icon would prevent unreadable overlap.

could you please address this? thank you for you time!

**Comment by theripper93** [comment]
that option is there to allign portraits that are now always centered, it's doing what it's supposed to, if you have issues with the target covering the effects, simply make it smaller.

**Comment by susscribe** [comment]
if i make it smaller enough to not cover it, then i cannot tell which token is targeting anymore, too small for targeting token icon to have a point for being there. is there any other solution where i can keep smart target's distinctive function intact?

**Comment by theripper93** [comment]
i'm afraid not - if you have the technical know how you are free to add in the code and send a PR to implement this new feature. if it's clean enough i'll add it in

**Comment by susscribe** [comment]
fair enough, it is beyond my abilities however. thank you for your time!
