### ISSUE TITLE
Suggestion: Use Lib DF Hotkeys

### ISSUE THREAD

**Issue by SalieriC** [theripper93/Smart-Target#32]
Using [Library: DF Hotkeys](https://foundryvtt.com/packages/lib-df-hotkeys) would make it a lot easier for users with multiple modules altering hotkeys to edit those and - possibly - resolve conflicts.

**Comment by theripper93** [comment]
i'm not planning to add dependincies or rework the hotkey system

**Comment by SalieriC** [comment]
I see. It was worth a shot though, having everything in one place is a far better user experience imo but I understand.
