### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by paulcheeba** [theripper93/Smart-Target#35]
Hello, got this error on load and it seems the current version has some compatibility issues and is removing the custom target marker from Easy Targets and Better Target modules and reverting the marker to foundry's default.
![image](https://user-images.githubusercontent.com/75949480/144755722-cea5db45-90b9-4f4c-b89b-27c84cccb2ed.png)
I don't know if the two issues are related.

**Comment by theripper93** [comment]
Are you using it with 2 other targeting modules? If so don’t , it’s normal that they don’t work together

**Comment by paulcheeba** [comment]
Ahhh, IC IC, I didnt realise your module included all the features those other two gave me. I've removed them both and there are no more errors.
