### ISSUE TITLE
Cant see what other players are targeting

### ISSUE THREAD

**Issue by TatianaKat** [theripper93/Smart-Target#40]
Hi there,

As the title suggests, I cannot see what my players are targeting when Smart Target is enabled, and I don't think they can see each others targets, either. Whenever I target anything as the GM, I get no error messages in the console, but when a player targets something, this error message pops up in the Java console:

https://i.gyazo.com/5a01bf4d0441a153536a834b3176af3d.png

**Comment by theripper93** [comment]
The only thing I can think of is the you are using cors blocked images - this means for example an image from an external url, while those will work in the html interface (eg charachter sheets) they will not in the scene

**Comment by TatianaKat** [comment]
I think this was the problem, my players were using imgur to host their token avatars. I asked them to upload them directly to Forge instead and it started working. Weird though, never had this problem before back when I was using Targeting Enhancements!

**Comment by theripper93** [comment]
It depends on the backend handling, anyways glad it’s solved
