### ISSUE TITLE
Feature Request:  No GM image when the NPC is not visible to player

### ISSUE THREAD

**Issue by ditzer252** [theripper93/Smart-Target#41]
It would be awesome if the indicators of hidden creatures that target a PC are just shown as the colored circles, not portraits, so as to not give away what the unseen creature was. 
Thanks!

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/#/faq/issues) and reopen the issue with all the relevant information.
