### ISSUE TITLE
Feature Request: Post target icon/name on action logs

### ISSUE THREAD

**Issue by kiloforce** [theripper93/Smart-Target#42]
Would be great if in the chat log a small message were included (or added to attack message) that includes something like "Target: (token icon)" for any attacks/abilities.  Looking at the chat logs, it is often very difficult to determine who was being targeting for an attack.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/#/faq/issues) and reopen the issue with all the relevant information.
