### ISSUE TITLE
[BUG] Libwrapper / SmartTarget warning loop

### ISSUE THREAD

**Issue by UnoriginalDM** [theripper93/Smart-Target#44]
**ALL OTHER MODULES DISABLED?** True* (LibWrapper Enabled)
**Module:** Smart Target ver 0.9.2
**Conflicting Module (if applicable)**: LibWrapper ver 1.12.8.0
**Foundry and System version**: Foundry ver 10.284 - Dnd 5e ver 2.0.2
**OS, Hosting, Browser (if applicable)**: Chrome
**Short Description of bug**: With LibWrapper and SmartTarget enabled, if you target a token you get a loop that keeps populating warnings eventually it bogs down FoundryVtt.
**Simple steps to reproduce the bug**: Enable both LibWrapper and SmartTarget. Target a token.
**Screenshots and/or console errors**:
![image](https://user-images.githubusercontent.com/77896718/188472492-851a0791-e6fb-4415-95b4-001e88da021a.png)

If I have an opportunity to dig into it and find a solution, I will let you know. Thank you for all your hard work.

**Comment by theripper93** [comment]
fixed
