### ISSUE TITLE
[Feature Request] Option to hide "clear all targets" button

### ISSUE THREAD

**Issue by marceloabner** [theripper93/Smart-Target#48]
I think that button is good, but with a lot of other modules removing targets at the end of a turn, or when defeated, and with keyboard shortcuts, that button can be redundant and we could save some space too.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/#/faq/issues) and reopen the issue with all the relevant information.
