### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by 9ryex5** [theripper93/Smart-Target#5]
Please give us the option to default this for token even if there is an avatar for the assigned actor.

![image](https://user-images.githubusercontent.com/43207603/120932149-9b98dc80-c6ec-11eb-921e-207b74bb7d10.png)

**Comment by theripper93** [comment]
that's easly doable for non gms, i will add it

**Comment by theripper93** [comment]
feature added in 0.4.5
