### ISSUE TITLE
Always Target doesnt work with templates

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [theripper93/Smart-Target#50]
When you have the always target setting on for players (which i would love to use)  when you drop down a template it doesn't auto target everything in the template.

Holding alt as you do it doesnt fix this either. 

Im using Pathfinder 2e 4.7.4 with the latest version of foundry.  v10 249

Additionally what would be great for the always target setting is to just drop a template and for it to target without the need to hold alt.

console error log here 
![image](https://user-images.githubusercontent.com/62528192/219908376-4e0f8cca-622d-454f-902c-6e3ae096d188.png)

**Comment by ThingsCouldGetDicey** [comment]
> You have to Alt+click in the template area (not in the template icon)

im not sure i understand because once it is placed it doesnt target. 
and ontop of that i cannot alt + click the templata area the only thing i can click is the template icon.

**Comment by theripper93** [comment]
There is no UI feedback, you just click in the area of the template on the canvas

**Comment by ThingsCouldGetDicey** [comment]
thank you i now understand
