### ISSUE TITLE
Feature Request: Support PF2e area rules more accurately

### ISSUE THREAD

**Issue by esheyw** [theripper93/Smart-Target#52]
Currently, if I have a 15ft diagonal cone, based on [pf2e area rules](https://2e.aonprd.com/Rules.aspx?ID=354), it should only target the grid spaces highlighted in this screenshot: 
![](https://i.imgur.com/2w8RI53.png)
however, if I use this modules alt-click-to-target-under-template feature, it is too greedy, and grabs anything over 50% covered by the base template area: 
![](https://i.imgur.com/zXMVPlk.png)
for orthogonal cones, it's fine up until 25ft:
![](https://i.imgur.com/CI4jZWK.png)
for a 5 foot emanation, which should be every space around a character, it only targets orthogonally (and includes the caster when it shouldn't: 
![](https://i.imgur.com/AK1usxf.png)
Bursts seem to work up until 15 feet and then the base template vs affected squares start disagreeing again: 
![](https://i.imgur.com/eaZ0Uu0.png)

Bursts and Emanations are both circle templates, but the system has them behave differently depending on if they're on a grid intersection or the centre of a space.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.

**Comment by theripper93** [comment]
I will add, that template targeting is not a main feature/focus of smart target, if pf2e has special rules, the system should implement the targeting itself
