### ISSUE TITLE
Warning in console in FVTT 11

### ISSUE THREAD

**Issue by ottyn** [theripper93/Smart-Target#53]
Get the following warning in the console when left clicking anywhere on an active scene.  System works normally, just strange warning message.

Foundry v11.301
PF2e 5.0-beta2
Smart Target 1.0.0

![image](https://github.com/theripper93/Smart-Target/assets/97130150/77fb00f4-ad68-47c1-a88e-070442043b32)

**Comment by theripper93** [comment]
fixed
