### ISSUE TITLE
As GM, GM image set to Token image shows players image instead of NPC's.

### ISSUE THREAD

**Issue by WaterpoloBlock** [theripper93/Smart-Target#54]
**I have disabled all other modules: **True
**Module(s) **Smart Target
**Conflicting Module(s) **None
**Foundry and System version **Foundry 11 (315), Game System (PF2e version 5.11.5)
**OS, Hosting, Browser (if applicable) **Windows 11, Forge, Brave
**Short description of bug **GM image set to Token image. For Players, instead of seeing the npc image targeting them. They will see there own image.
**Simple steps to reproduce the bug **

Confirm Module is enabled, go to Game settings -> Configure Settings -> Smart Target-> Make sure "Show indicator portraits instead of color" and "use Tokens instead of Avatars" are enabled. Set Gm image to "Token Image"

In the picture, the left most pic is me as a GM and what I see. Right most pic is what the players see.

**Screenshots and/or Console Errors**

![Target_Error](https://github.com/theripper93/Smart-Target/assets/73310678/037cba26-c7d5-40cc-ab55-b110d8599842)

**Comment by theripper93** [comment]
Fixed
