### ISSUE TITLE
[Request] Switch between targets that stack

### ISSUE THREAD

**Issue by Witchcrafter1** [theripper93/Smart-Target#55]
In the case that multiple tokens occupie the same place/cell, it would be nice if there was a simple solution to switch between them and target the correct one. This could be done via costum keybinds (arrow up/down), or Icons above the target token that indicate that there are (multiple) possible target in the same location.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
