### ISSUE TITLE
Alt-click not working

### ISSUE THREAD

**Issue by DariusWolfe** [theripper93/Smart-Target#56]
**I have disabled all other modules:** True
**Module(s)** Smart Target
**Conflicting Module(s)**
**Foundry and System version** Foundry v12 build 329, PF2e v6.0.4
**OS, Hosting, Browser (if applicable)** Linux Mint 21.3 (64bit), FVTT built-in browser
**Short description of bug:** Alt-click does not select target
**Simple steps to reproduce the bug**

1. Enable Alt-click or Always Target
2. As a GM-Alt-click the target
3. As a player, Alt-click the target if Alt-click is enabled
4. It will not target.

**Screenshots and/or Console Errors**
There are no console errors.

**Comment by theripper93** [comment]
Please provide the module version and re open the issue

**Comment by DariusWolfe** [comment]
Version 2.0.0
