### ISSUE TITLE
Target indicator to big 

### ISSUE THREAD

**Issue by LordOHelmet** [theripper93/Smart-Target#7]
All options in the module are enabled. The size options are all on default.
I get this result, with the target indicator overlapping the target way to much.
![Target](https://user-images.githubusercontent.com/80178910/121479326-33871680-c9ca-11eb-9d02-b524d8c40dea.JPG)
Is this an issue with the scaling of the grid? Because on other scenes it works just fine.

**Comment by theripper93** [comment]
ye it's probably a grid scale issue - drawing custom shapes from polygons is kinda complicated :P might fix some day but it's a lot of work and i'm currently very busy with other modules
